services:
  syzkaller:
    build: .
    container_name: javigod-epa-evosuite
    stdin_open: true 
    tty: true
    privileged: true
    entrypoint: /usr/bin/bash
    volumes:
      - /home/dwappner/Desktop/enabledness-based-testing-jgodoy/epa-benchmark:/replication-package/epa-benchmark
    restart: "no"
